server:
  port: 8080

spring:
  application:
    name: msvc-gateway

  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=X-Gateway, "Spring Cloud Gateway"
      server:
        webmvc:
          routes:
            # Microservicio Monopat�n
                      - id: msvc-monopatin
                        uri: http://localhost:8081
                        predicates:
                          - Path=/api/monopatin/**

                      # Microservicio Usuario
                      - id: msvc-usuario
                        uri: http://localhost:8082
                        predicates:
                          - Path=/api/usuario/**

                      # Microservicio Cuenta
                      - id: msvc-cuenta
                        uri: http://localhost:8083
                        predicates:
                          - Path=/api/cuenta/**

                      # Microservicio Parada
                      - id: msvc-parada
                        uri: http://localhost:8084
                        predicates:
                          - Path=/api/parada/**

                      # Microservicio Facturaci�n
                      - id: msvc-facturacion
                        uri: http://localhost:8085
                        predicates:
                          - Path=/api/facturacion/**

                      # Microservicio Viaje (MongoDB)
                      - id: msvc-viaje
                        uri: http://localhost:8086
                        predicates:
                          - Path=/api/viaje/**

                      # Microservicio Administraci�n
                      - id: msvc-administracion
                        uri: http://localhost:8087
                        predicates:
                          - Path=/api/administracion/**

                      # Microservicio Reporte
                      - id: msvc-reporte
                        uri: http://localhost:8088
                        predicates:
                          - Path=/api/reporte/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: INFO