spring:
  application:
    name: msvc-usuario

  datasource:
    url: jdbc:mysql://localhost:3306/usuario_db?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ""

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            # Microservicio Monopat?n
            - id: msvc-monopatin
              uri: http://localhost:8081
              predicates:
                - Path=/api/monopatin/**

            # Microservicio Parada
            - id: msvc-parada
              uri: http://localhost:8084
              predicates:
                - Path=/api/parada/**

            # Microservicio Facturaci?n
            - id: msvc-facturacion
              uri: http://localhost:8085
              predicates:
                - Path=/api/facturacion/**

            # Microservicio Viaje (MongoDB)
            - id: msvc-viaje
              uri: http://localhost:8086
              predicates:
                - Path=/api/viaje/**

            # Microservicio Administraci?n
            - id: msvc-administracion
              uri: http://localhost:8087
              predicates:
                - Path=/api/administracion/**

            # Microservicio Reporte
            - id: msvc-reporte
              uri: http://localhost:8088
              predicates:
                - Path=/api/reporte/**

server:
  port: 8080