spring:
  application:
    name: msvc-usuario

  datasource:
    url: jdbc:mysql://localhost:3306/usuario_db?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ""

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: msvc-monopatin
              uri: http://localhost:8081
              predicates:
                - Path=/api/monopatin/**
            - id: msvc-parada
              uri: http://localhost:8084
              predicates:
                - Path=/api/parada/**
            - id: msvc-facturacion
              uri: http://localhost:8085
              predicates:
                - Path=/api/facturacion/**
            - id: msvc-viaje
              uri: http://localhost:8086
              predicates:
                - Path=/api/viaje/**
            - id: msvc-reporte
              uri: http://localhost:8088
              predicates:
                - Path=/api/reporte/**
            - id: msvc-mockMercadoPago
              uri: http://localhost:8089
              predicates:
                - Path=/api/mp/**

server:
  port: 8080

springdoc:
  swagger-ui:
    urls:
      - name: MSVC Usuario (gateway)
        url: http://localhost:8080/v3/api-docs
      - name: MSVC Monopatin
        url: http://localhost:8081/v3/api-docs
      - name: MSVC Parada
        url: http://localhost:8084/v3/api-docs
      - name: MSVC Facturacion
        url: http://localhost:8085/v3/api-docs
      - name: MSVC Viaje
        url: http://localhost:8086/v3/api-docs
      - name: MSVC Reporte
        url: http://localhost:8088/v3/api-docs
